In [116]:
import numpy as np

## Python Lists

A list is created using square brackets, with elements separate by comma. Some common functions of a list are given below.


In [117]:
listA = [2,8,6,4,12]
print(listA)

listA.sort() #sorts your list from least to greatest value
print(listA)

listA.pop(1) #pop is a function used to temporarily delete the chosen index
print(listA)


[2, 8, 6, 4, 12]
[2, 4, 6, 8, 12]
[2, 6, 8, 12]


### Slicing

Python counts differently from us! While we count 1,2,3,4,5, Python counts 0,1,2,3,4,5. Therefore, Python indexing starts at 0. This means if you have a list [3,6,9,12], the first value 3 would have index 0. The second value, 6, would have index 1 and so on. See below for how to call certain values from a list.

In [118]:
myList = [1,1,2,3,5,8,13]
print(myList[0])

print(myList[2])

print(myList[-1]) #negative indexing counts from the end [-1] backwards


1
2
13


To slice a range of values in your list, we use a colon. 

In [119]:
myList = [1,1,2,3,5,8,13]

print(myList[0:6]) #the first term in the list (0) to the second to last term; 
#note this function is not inclusive of the last index [6]

print(myList[2:]) #from the third term in the list to the end of the list

[1, 1, 2, 3, 5, 8]
[2, 3, 5, 8, 13]


### Linspace, arange, zeros, oh my!

Common NumPy functions to create a list are np.linspace and np.arange. They are very similar functions that can do the same thing.  Use whichever you prefer! These functions are helpful so you do not have to manually type out every list you want to make in Python.

Linspace works with the function np.linspace(first#, last#, how many values between these two numbers).

To make a list of zeros, simply use np.zeros(# of zeros you want).  This is a useful list when you want to use a for loop and fill in the zeros with values. 

In [120]:
lin_list = np.linspace(1,10,10)
print(lin_list)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


Arange works with the function np.arange(first#, last# + 1, increment of counting). 

You can use arange without specifying the first number and increment, too.  By default, arange will start counting at 0 and give you the specified number of indices. See below for clarification.  

In [121]:
arange_list = np.arange(1,10,1)
print(arange_list)

countby2 = np.arange(2,11,2)
print(countby2)

arange_list2 = np.arange(10) #notice how this list starts at 0 and ends on 9, giving you 10 indices
print(arange_list2)

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]


In [122]:
zero_list = np.zeros(8)
print(zero_list)

zero_list2 = zero_list + 2
print(zero_list2)

[0. 0. 0. 0. 0. 0. 0. 0.]
[2. 2. 2. 2. 2. 2. 2. 2.]


### Practice

Use linspace and arange to make a list counting from 0 to 15 counting by 3s [0,3,6,9,12,15]

## For Loops

A for loop is used for iterating over a sequence (such as a list, array, or string).  There are many ways to format a for loop, you can even have a for loop within a for loop! For this tutorial, we'll just concern ourselves with the basics of a for loop and the format we use for XRD analysis. 

#### range() function

To loop through a set of code a specified number of times, we can use the range() function. The range function works very similarly to np.arange. 

The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number. You can put a specified number or variable within the parenthesis.  

Always start a for loop with for.  Following for can be any variable, commonly x, i, and n, but you can use any variable that makes sense to you. Then we put our range() function followed by a colon.  

In [123]:
#a simple for loop
for x in range(6): #notice how the return starts at 0 and ends at 5, giving you 6 total indices
    print(x)  

0
1
2
3
4
5


In [124]:
for x in range(2,6): #you can specify you're starting value as well
    print(x)

2
3
4
5


In [125]:
lattice = np.zeros(8) 

for n in range(8):
    lattice = lattice +1
    print(n) #where you put the print statement matters, within the for loop prints all iterations
print('outside of the for loop =', n)#outside of for loop prints last iteration only

0
1
2
3
4
5
6
7
outside of the for loop = 7


While the for loops we use in lab are a little more complicated than the ones discussed here, they are built upon the same basics.  For loops take a lot of practice, patience, and trial & error.  Even writing this for loop below took me several tries.  That being said, for loops are extremely useful for many doing calculations over many iterations.

See below for a for loop that coverts degrees to radians and combines many of the topics in this tutorial.

In [126]:
degrees = np.linspace(0,90,7)
print(degrees)

for n in range(7):
    radians = (degrees[n]*np.pi)/180 #convert from 2-theta to theta in radians
    print(radians)

[ 0. 15. 30. 45. 60. 75. 90.]
0.0
0.2617993877991494
0.5235987755982988
0.7853981633974483
1.0471975511965976
1.3089969389957472
1.5707963267948966
